### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by jhosoume** [EngSwCIC/PleaseDontDie#2]
Como usuário, quero cadastrar meu e-mail e senha para fazer LogIn.

**Comment by jonataasgoomes** [comment]
Como usuário quero utilizar meu e-mail e senha cadastrados para fazer LogIn

**Comment by jhosoume** [comment]
Fica melhor do jeito que o JJ escreveu, vou editar a descrição de "Como usuário após me cadastrar na plataforma quero logar para que consiga ver meus dados pessoais.", para "Como usuário quero utilizar meu e-mail e senha cadastrados para fazer log in."
