### ISSUE TITLE
Adicionar tarefas/lembretes para os usuarios em relação aos pets

### ISSUE THREAD

**Issue by jonataasgoomes** [EngSwCIC/PleaseDontDie#6]
Como usuário já cadastrado , após adicionar meus pets , quero adicionar/modificar tarefas e lembretes relacionados a cada um deles.

**Comment by jhosoume** [comment]
Podemos dividir em dois categorias diferentes? Por exemplo, tarefas seria dadas a usuários e necessidades estaria relacionadas diretamente com os Pets?

**Comment by jonataasgoomes** [comment]
Como seria Ju?  eu pensei em tarefas/lembretes sendo uma categoria só assim: Quando um usuário cadastrar por exemplo uma tarefa: Vacinar ou então Alimentar ... etc - ela poderia adicionar a esta tarefa uma time-line de quando deveŕa ser concluída a tarefa. Como deve ser feita pra dividir ?

**Comment by jhosoume** [comment]
Vamos rever o ERD e decidir isso aí numa próxima reunião, acho que fica mais fácil.
